services:
  ihm3:
    build: .
    container_name: neodocjtext
    ports:
      - "9980:80"
    restart: always
    volumes:
      - /home/virtus/clara_2026/neo4_final/:/app

networks:
  default:
    external:
      name: virtus

